__title__ = 'rstParser'
__summary__ = 'A parser for reStructuredText documents'
__url__ = 'https://github.com/rblack42/rstParser'
__version__ = '0.1-dev'
__author__ = 'Roie R. Black'
__email__ = 'rblack@austincc.edu'
__license__ = 'BSD 3-Clause'
